### ISSUE TITLE
Add algolia search

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/oc-documentation#100]
Official [gatsby guide](https://www.gatsbyjs.org/docs/adding-search-with-algolia/) for adding algolia search to a gatsby site.

The guide mentions optionally using [DocSearch by algolia](https://community.algolia.com/docsearch/what-is-docsearch.html) which is a completely free option but is a bit limited. The indexer runs every 24h and they don't index blogs. I think we want finer grained control so we'll probably want to go for the paid.

**Comment by djsteinmetz** [comment]
I'd love to work on this one @crhistianramirez

**Comment by crhistianramirez** [comment]
complete
