### ISSUE TITLE
Add a "Getting Started" section to the homepage

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/oc-documentation#106]
This section is currently missing. We'll need to update the design/layout on the homepage to accomodate for 4 section cards instead of 3.

**Comment by esitarz** [comment]
This should be API Reference now, right? not Getting Started?
![Screenshot_2019-08-13 OrderCloud Release Notes - undefined](https://user-images.githubusercontent.com/18353755/62982700-9d483080-bdf2-11e9-999a-f617c39986bd.png)

**Comment by crhistianramirez** [comment]
No the task is written correctly. Api reference will be a single page that will get linked to from the vertical nav.

It does look kinda funny though now that I see it. What does everyone else think?

**Comment by amrarick26** [comment]
It does look weird. I thought I had those filtered out using the hidden property in the front matter of the markdown files?

**Comment by crhistianramirez** [comment]
Yeah, but I also thought you were a proponent on being displayed as a section to give more visibility to it. I'm ok with axing it now that i see it lol

**Comment by amrarick26** [comment]
I thought having it as the buttons in the huge section above was enough? It seems redundant now.

**Comment by crhistianramirez** [comment]
Closing this. Twas a silly task
