### ISSUE TITLE
New Guide: Impersonation

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/oc-documentation#107]
We're always getting questions about impersonation and should really have a guide on it. There will be two parts to this:

1. Feature guide - high level overview catered to business user type that describes what impersonation is and why they might want to use it. Should link to guide (part 2)
2.  Guide - Gets into detail, shows API calls, talks about impersonation configs and what the fields mean and are.

**Comment by amrarick26** [comment]
Moved to Jira
