### ISSUE TITLE
API Reference: General Design

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/oc-documentation#146]
Let's clean it up for launch 🚀

**Comment by robertsoniv** [comment]
Routes:
- `/api-reference/:section` => SectionPage
- `/api-reference/:section/:resource` => ResourcePage (with all operations)
- `/api-reference/:section/:resource#:operation` => Currently Viewed Operation

Context:
- DocsTree => All Sections/Resources/Operations (ID and Name for each) to create the navigation

Navigation Design Changes:
- Sections
-- Always expanded
-- onClick => view section page
- Resources
-- onClick => expand operations & view top of resource page
- Operations
-- onClick => update #operation in address bar & scroll to operation

Resource Page:
- As users scroll, change the #operation in address bar to match operation most in view
