### ISSUE TITLE
Doesn't show you're signed in if you are

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/oc-documentation#147]
Steps to recreate:
1. Navigate to https://oc-portal-test.azurewebsites.net/login and login
2. Navigate to https://oc-docs-test.azurewebsites.net/ and observe the call to action to "Login". 

Expected results:
Should show your gravatar

**Comment by robertsoniv** [comment]
@crhistianramirez @jilse 
Until we have a custom domain (oc-docs-qa.ordercloud.io or something) we won't be able to share tokens on the root domain (azurewebsites.net).

Maybe we can figure something out for localhost in the meantime.

**Comment by robertsoniv** [comment]
@crhistianramirez this should be fixed on portal.ordercloud-qa.com and docs.ordercloud-qa.com
