### ISSUE TITLE
Create Devcenter Release Notes 

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/oc-documentation#157]
Now that devcenter is part of the platform we'll need to have a release notes for them as well. Part of this task should be creating the initial release notes. Can probably piggy back off of this

https://docs.google.com/document/d/1Mki9VDrVYcb-myGh5S_FJL93PpRcV_sibiJrfZtqb3Y/edit

**Comment by robertsoniv** [comment]
@sydneycasey has this task been completed?

**Comment by crhistianramirez** [comment]
This is complete but we'll need to update the placeholder text with our first release not before go-live 

http://docs.ordercloud-qa.com/portal-release-notes/v1.0.0
