### ISSUE TITLE
API release notes landing page design

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/oc-documentation#56]
Currently it's pretty bare bones:
![image](https://user-images.githubusercontent.com/16483662/62479585-6c715700-b773-11e9-8ac0-a50bfe6d49bf.png)

Might be a purely design task unless there's other data points that could get fed into this template that might help with design?

**Comment by esitarz** [comment]
test comment!

**Comment by esitarz** [comment]
test comment, take 2!

**Comment by esitarz** [comment]
take 3!
