### ISSUE TITLE
404 Not Found Page

### ISSUE THREAD

**Issue by djsteinmetz** [ordercloud-api/oc-documentation#72]
Design for `404 Not Found Page`

**Comment by crhistianramirez** [comment]
@djsteinmetz  this page (when served) is actually going to be the one defined in portal "No Match Component"

Its a little complicated but any 404's get handled by that app. let me know if you have any questions

**Comment by djsteinmetz** [comment]
Oh, ok, makes sense.  It's because of the uni-hosting right? - so we can just close this issue?

**Comment by crhistianramirez** [comment]
Yeah, might be worth creating an issue on the portal backlog
