### ISSUE TITLE
Main Page Responsiveness

### ISSUE THREAD

**Issue by djsteinmetz** [ordercloud-api/oc-documentation#83]
The main page needs to be optimized at each view port.  There is some weirdness happening with the main 3 cards, as well as the footer having too much margin.

**Comment by esitarz** [comment]
i've got some fixes for these

**Comment by djsteinmetz** [comment]
For which? I'm also working on it, and don't want any merge conflicts :me--sad:

**Comment by esitarz** [comment]
:oh-no: both the marginBottom on the footer and the Jumbotron size.
pretty covert fixes: just added a few media queries.

**Comment by djsteinmetz** [comment]
Lol, I have fixes for both those in my branch as well.

**Comment by esitarz** [comment]
oh ok! no frets! Mine are just: 
``` jumbotron: {
      height: '50vh',
      [theme.breakpoints.down('md')]: {
        height: '75vh',
      },
```

and 

```
root: {
 [theme.breakpoints.up('md')]: {
        marginBottom: theme.spacing(55),
      },
},
```
