### ISSUE TITLE
Expand Navigation on Hover (Better UX)

### ISSUE THREAD

**Issue by djsteinmetz** [ordercloud-api/oc-documentation#91]
On hover, expand the vertical navigation bar to expose full F51 OC logo + verbiage of what each menu item is.  This will reduce people having to guess what each icon means.

**Comment by esitarz** [comment]
https://chrome.google.com/webstore/detail/muzli-2-stay-inspired/glcipcfhmopcgidicgdociohdoicpdfc #

**Comment by djsteinmetz** [comment]
Getting there... Attempting it with pure CSS, not sure if it's the way to go.  Now just have to figure out some other semantic things like:
1. Should the whole link (text too) be clickable - will probably need to switch away from icon button
2. How to get complex enough css to show links on parent element hover (@esitarz I know you can come in clutch with the save on this one)


![hovermenu](https://user-images.githubusercontent.com/38231097/62718232-126ace80-b9cb-11e9-9883-07df125e6c19.gif)

**Comment by crhistianramirez** [comment]
1. Yes I think the links should definitely be clickable, yep probably can't use icon button anymore but that's ok, I'm sure there's some pattern we can find. Here's one I found for list, not sure if applicable:
```
<ListItem button onClick={handleClick}>
    <ListItemIcon>
    <InboxIcon />
    </ListItemIcon>
    <ListItemText primary="Inbox" />
        {open ? <ExpandLess /> : <ExpandMore />}
</ListItem>
```
2. :ralph:

**Comment by esitarz** [comment]
nice one! I say go for the CSS route!

Yeah I'd swap the FABs to a [MUI list](https://material-ui.com/components/lists/)

Then for show the parent links, I bet you can get away with put the hover on the entire parent, which makes life much easier:
```
sideNav: {
   width: {single icon width},
   '&:hover' {
      width: {icon + text width},
    },
}
```

**Comment by djsteinmetz** [comment]
Heck yeah, that was the ticket Eric... MUI List for life
(in code sandbox)
![hovermenu--list](https://user-images.githubusercontent.com/38231097/62725285-75179680-b9da-11e9-9f28-5781ad376130.gif)

**Comment by crhistianramirez** [comment]
That looks so slick!
