### ISSUE TITLE
Docs Template: MDXProvider on the MDXRenderer

### ISSUE THREAD

**Issue by esitarz** [ordercloud-api/oc-documentation#94]
Problem:
```
<Typography>
  <MDXRenderer>{post.mdx.body}</MDXRenderer>
</Typography>
```
This does not work. Material Theme Fonts are not getting passed into this element. Need to leverage MDXprovider to make sure rendered content gets the Material Styles.

**Comment by crhistianramirez** [comment]
Am I looking at this wrong? When I inspect the elements I see "Geometria" which seem to be the font we have?

![image](https://user-images.githubusercontent.com/16483662/62741859-0d754180-ba02-11e9-9ab3-d14bfa4586bd.png)

**Comment by esitarz** [comment]
no sir, you are seeing that correctly. We are declaring the correct font in our stack:
```
"CoreSans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
```
however the font being rendered _(on my machine, and probably will be different on yours)_ is `-apple-system`.
This leads me to believe the `<Typography>` wrapper isn't reaching the markdown within the `<MDXrenderer>`

**Comment by esitarz** [comment]
also-- peep that tsx real quick:
```
<Typography
                className={classes.postTitle}
                variant="h4"
                component="h1"
              >
                {post.mdx.frontmatter.title}
              </Typography>
              <Typography>
                <MDXRenderer>{post.mdx.body}</MDXRenderer>
              </Typography>
```

`Geometria` is the heading font for all h1-h6. It's working as expected on the h1 because it's outside the `<MDXRenderer>`.
