### ISSUE TITLE
Create graphics for "Main Concepts" docs

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/oc-documentation#97]
1. [Organization Hierarchy](https://orderclouddocs.z19.web.core.windows.net/documentation/main-concepts/organization-hierarchy)
    - pretty low-fi mockup made by yours truly there. Please for the love of god replace it with something better
2. [Catalog Hierarchy](https://orderclouddocs.z19.web.core.windows.net/documentation/main-concepts/catalog-hierarchy)
    - graphic of a category tree
    - graphic of a category tree *within* a catalog
    - graphic of a category hierarchy within a catalog *with* product assignments. Products should live *outside* the catalog
3.  [Product Visibility](https://orderclouddocs.z19.web.core.windows.net/documentation/main-concepts/product-visibility)
    - graphic representing a three point assignment between a product, a priceschedule and a usergroup
    - graphic representing an assignment between a usergroup, a product and price schedule and then the same product assigned to a different usergroup with a different price schedule. 
    - Bonus: there's a "Product Visibility Cheat Sheet" at the bottom, any way we could spice this up a bit more? :thinking:

Might be a good brogramming sesh to cook up the best way to represent these.

**Comment by amrarick26** [comment]
Moved to Jira https://four51.atlassian.net/browse/OCDOC-9
